### ISSUE TITLE
Add to cocoapods.org

### ISSUE THREAD

**Issue by yelled3** [aleclarson/emitter-kit#1]
All add info on how to install in README.md

@aleclarson WDYT?

**Comment by gscalzo** [comment]
since 0.36.1.beta, Cocoapods is compatible with Swift.
Other Swift frameworks are beginning to include Cocoapods support.

**Comment by yelled3** [comment]
:+1: @gscalzo 

@aleclarson  WDYT?

**Comment by aleclarson** [comment]
I would love to add Cocoapods support when I get the free time. I don't use Cocoapods myself, so it will take some effort to figure it out. Thus, this is not my top priority right now.

Thanks for your interest, everyone!

**Comment by somekool** [comment]
I tried to load this via carthage and I am getting this error, seems like nothing is happening

```
13:18 ~/Projects/adeke (master)$ cat Cartfile
github "aleclarson/emitter-kit" "master"

13:18 ~/Projects/adeke (master)$ carthage update
*** Fetching emitter-kit
*** Checking out emitter-kit at "cbfabcb9e5ab2b2e8cb896978003ea8c9d82768a"
*** xcodebuild output can be found in /var/folders/vv/rgts3xks40v31wklf78_5bn80000gn/T/carthage-xcodebuild.j5dXza.log
Project "EmitterKit.xcodeproj" has no shared schemes
13:19 ~/Projects/adeke (master)$ cat /var/folders/vv/rgts3xks40v31wklf78_5bn80000gn/T/carthage-xcodebuild.j5dXza.log
13:19 ~/Projects/adeke (master)$ ls -la /var/folders/vv/rgts3xks40v31wklf78_5bn80000gn/T/carthage-xcodebuild.j5dXza.log
-rw-------  1 somekool  staff  0 14 Jan 13:19 /var/folders/vv/rgts3xks40v31wklf78_5bn80000gn/T/carthage-xcodebuild.j5dXza.log
13:36 ~/Projects/adeke (master)$

```

**Comment by aleclarson** [comment]
`3.2.1` should now be available in CocoaPods. :wink:

Let me know if you have any trouble.

**Comment by yelled3** [comment]
@aleclarson thanks :+1:
