### ISSUE TITLE
Building with Swift 1.2

### ISSUE THREAD

**Issue by mkoppanen** [aleclarson/emitter-kit#12]
There are currently several issues with the build after the latest Xcode update (6D520o). We are looking at these locally and probably have a patch during today. 

How are you handling backwards incompatible changes at the moment? After the updates the code will only compile with Swift 1.2 as there is no proper support for conditional compiling in the language.

**Comment by aleclarson** [comment]
I just pushed 181cc69 and tagged it with `3.2.0`. Thank @cakper for submitting the fixes. :+1: 

I also created tags for past versions in case someone wants to use an older version of Swift.
