### ISSUE TITLE
Swift 2.0 support

### ISSUE THREAD

**Issue by danyalaytekin** [aleclarson/emitter-kit#18]
EmitterKit does not compile with Swift 2.0, in Xcode 7 beta.

![image](https://cloud.githubusercontent.com/assets/1315042/8157296/9cb255c0-134b-11e5-88f2-6816c366b581.png)

**Comment by aleclarson** [comment]
Hmm, I imagine these errors aren't that difficult to fix.

Unfortunately, I don't currently have spare time to make this update.

Perhaps someone else will come in with a pull request.

Sorry for any inconvenience this may cause you!

**Comment by nubbel** [comment]
I probably have time for that this week.

**Comment by aleclarson** [comment]
Awesome work, @nubbel. Thanks for helping out!

**Comment by nubbel** [comment]
@aleclarson You're very welcome! May I suggest a major version bump to 4.0, because this change is not backwards compatible?

**Comment by aleclarson** [comment]
@nubbel That's a good point! :smile:

**Comment by danyalaytekin** [comment]
1) 

Thanks @aleclarson @nubbel, much appreciated.

2) 

This change does break Swift 1.2 though, which is still the standard version, so I'm not sure it should have been applied to `master`.  [Some](https://github.com/Hearst-DD/ObjectMapper/tree/swift-2.0) [other](https://github.com/Alamofire/Alamofire/tree/swift-2.0) [projects](https://github.com/pkluz/PKHUD/tree/swift-2.0) are using a `swift-2.0` branch.

**Comment by nubbel** [comment]
@danyalaytekin I share your concerns. However, I think this project is more or less stale. I don't expect many changes in the next few months. If an app requires Swift 1.2 it can target the 3.x version using CocoaPods.

**Comment by danyalaytekin** [comment]
@nubbel :+1:
