### ISSUE TITLE
4.0.0 not appearing in Cocoapods

### ISSUE THREAD

**Issue by danyalaytekin** [aleclarson/emitter-kit#22]
Do you need to push the new podspec?

https://guides.cocoapods.org/making/getting-setup-with-trunk

**Comment by danyalaytekin** [comment]
Also please note that rewriting git history in origin will cause problems with people's CocoaPods installations.

**Comment by nubbel** [comment]
:+1:

**Comment by aleclarson** [comment]
I've updated `emitter-kit` to `4.0.1` on CocoaPods. Hopefully that's good enough. :+1:
