### ISSUE TITLE
Xcode 7 beta 4 support

### ISSUE THREAD

**Issue by danyalaytekin** [aleclarson/emitter-kit#24]
Swift 2 has changed in this beta, and emitter-kit no longer compiles.

**Comment by jtianling** [comment]
Just have a problem in Helpers.swift, because in new version, the Array of swift change the template type name to Element from T.

**Comment by bagusflyer** [comment]
Get compile error in line 124 in ChangeListener. swift. Error message is:

> /EmitterKit/ChangeListener.swift:124:17: Method does not override any method from its superclass

**Comment by aleclarson** [comment]
Sorry the delay, guys! I've been very busy! :smile:
