### ISSUE TITLE
how to user   

### ISSUE THREAD

**Issue by yanglichuan** [aleclarson/emitter-kit#26]
please  upload the demo

**Comment by SamDecrock** [comment]
or an example on how to start

**Comment by SamDecrock** [comment]
just noticed documentation is in the wiki: https://github.com/aleclarson/emitter-kit/wiki

**Comment by jonasman** [comment]
the docs are a bit poor. more examples would be welcome

**Comment by josephbeuysmum** [comment]
in the terminal:

My-MacBook-Pro:Emitter101 myname$ pod install
Updating local specs repositories
...
fatal: repository 'github.com/aleclarson/emitter-kit.git' does not exist

???

**Comment by aleclarson** [comment]
Sorry for the lack of communication, guys! I'm extremely busy these days. Plus, I'm not actively using this library. Hopefully you can figure things out on your own. Good luck!
