### ISSUE TITLE
listenerCount returns wrong value

### ISSUE THREAD

**Issue by aleclarson** [aleclarson/emitter-kit#44]
The `listenerCount` property of the `Event` class is currently computed with `_listeners.count`. That's not right, since the `_listeners` dictionary uses target identifiers for its keys; not listener identifiers.

This will get fixed at the same time as #43.

**Comment by Mattijah** [comment]
Should the `listenerCount` return number of all listeners? Sum listeners for all the targets?

**Comment by aleclarson** [comment]
I think it's rather useless to return all listeners of an event. Instead, we should probably just add a `getListeners(target?)` method for getting the array of listeners for the given target (or the array of listeners without a target if no target is given).

**Comment by aleclarson** [comment]
Added `getListeners` in v5.2.0 🎉 

ac1c9c96fba3d548c69bed012c699ed35b7ab3c5
