### ISSUE TITLE
5.2.0 release notes?

### ISSUE THREAD

**Issue by edenman** [aleclarson/emitter-kit#51]
Just curious what changes went into this release.

**Comment by aleclarson** [comment]
Is [this list](https://github.com/aleclarson/emitter-kit#v520-changelog) what you're looking for? 😁

**Comment by edenman** [comment]
Ah cool.  I saw some release notes on https://github.com/aleclarson/emitter-kit/releases but not 5.2.0, didn't think to look in the readme :)

**Comment by aleclarson** [comment]
@edenman Good point! I'll add them there, too. Thank you! 👍
